### ISSUE TITLE
Autothrottle

### ISSUE THREAD

**Issue by matthew007800** [magknight/787aviatorsTracker#107]
-Auto throttle does not switch to CONT upon takeoff and will stay on Takeoff derate until manually changed

-Auto Throttle will not power up in descent leading to a stall on several occasions

-Reverse thrust powers to 101N1

**Comment by aeroniemi** [comment]
there's no intention to include automatic throttle mode switching in 1.4.0, reverse isn't under the control of the limiter/auto throttle

**Comment by aeroniemi** [comment]
can you see if the descent stall issue is also occurring when on manual throttle but with autorhtotle armed, so we can tell whether its auto throttle or limiter based

**Comment by Sp33dM** [comment]
This problem is easy to replicate and straight forward.

-put your plane in holding altitude and manual thrust, autopilot should be on.

- arm the autothrottle and click on A/T button until lit up. 

-you will notice that the engines will go down to idle and stall the plane.

-however if you click FLCH with A/T, the throttles will remain on full power, but doesn't follow the assigned IAS

**Comment by aeroniemi** [comment]
i'm not seeing either of those issues directly, although in FLCH it doesn't accel/decel using pitch very quickly (although that's nothing new)
