### ISSUE TITLE
External sounds heard on the right side when setting up wing view

### ISSUE THREAD

**Issue by Bill-Clinton69** [magknight/787aviatorsTracker#223]
**Describe the bug**

When the camera is positioned just outside the aircraft on the right wing, external sounds can be heard. On the left wing, internal sounds are still heard. This is useful for setting up wing views to give users a clear unobstructed view of the wing and scenery while still listening to the internal engine sounds.

**To Reproduce**

Move the camera towards the passenger windows on the right side of the aircraft and position the camera just outside the windows to try to set up a wing view.

**Expected behavior**

Internal sounds of the engine should be heard, just like on the left side of the aircraft. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - X-Plane version 11.40r2
 - Version 1.4.0beta7

**Comment by Sdozer** [comment]
I can confirm this behavior, although is realistic that if the camera is outside the plane you'll hear outside sounds. But, I confirm that the positioning of the sounds are not OK since I was looking from inside the right side of the aircraft near the window and was hearing outside sounds, this is awkward, if I take the camera centimeters behind the outter sounds disappear and we'll hear the expected sound.

**Comment by audiobirdxp** [comment]
Will check it out. The boundaries were set up when I didn't have an actual 3D cabin for the aircraft.

**Comment by audiobirdxp** [comment]
Fixed. I set it up so you move a little bit just outside of the window with internal sounds (for setting up those views).
