### ISSUE TITLE
Feature suggestion: block throttles on A/T engage

### ISSUE THREAD

**Issue by verandaguy** [magknight/787aviatorsTracker#267]
This is a feature present in the Zibo 737 which helps prevent accidental disengagement of the autothrottle if the hardware throttle is moved too much. When this feature is turned on and A/T is engaged, it ignores all throttle axis inputs.

This also helps eliminate simulated throttle bouncing if the hardware throttle has poor integrated debouncing.

**Comment by aeroniemi** [comment]
I'm up for doing this, if we can find solutions for this issue:
How do you disconnect the autothrottle? - the real way to do it is by moving the throttles, but this removes the ability to do that. the only other way is by turning the arm switches to off, which is non-ideal. Unlike the 737, you aren't able to turn off the autothrottle just by clicking the A/T button (that does other stuff)

**Comment by verandaguy** [comment]
Right now, I've got no clue. Never programmed for X-Plane (or any other simulator). If you can tell me whether this is handled by XP native hooks or in the Java layer, I can dig around some API docs after work today, though.

I'll also see about getting my hands on an FCOM PDF to see what paths lead to an A/T disengage.

**Comment by aeroniemi** [comment]
It's not a actual implementation issue, we can deal with that by routing it through the autothrottle management system, it's just a question of how a user would disconnect it without that option

**Comment by verandaguy** [comment]
Good question. What about triggering it via the disconnect button on the side of the throttle instead of the AT button on the MCP?

**Comment by aeroniemi** [comment]
we intentionally chose not to model the disconnect buttons on the throttles as part of the autothrottle redesign because the vast majority of users don't have a button to map it to, and it is very unwieldy to have to go do it in 3d.The alternative chosen was if throttle input is detected, we disable it - this feature request specifically removes that as an option, so an alternative solution to the same effect would need to be designed - the reasons for not having the buttons still exist with this option on
