### ISSUE TITLE
some knobs turning unwanted to the most left value/zero on mouse click

### ISSUE THREAD

**Issue by Hinkelstein2** [magknight/787aviatorsTracker#470]
**Describe the bug**
the followings knobs jumping to the most left value on click. This should not happen, One time a knob became unresponsible afterwards.

PNL/FLOOD knob both sides
MAP knob both sides
FLT DECK TEMP and CABIN TEMP at the overhead panel

**To Reproduce**
just click on it

**Expected behavior**
if already there, they could work like in 1.5.1 or should work like some other knobs(APU start/ Hydraulic/ INBD DISPL/CONTRAST etc.)

**Desktop (please complete the following information):**
 - OS:Windows 10
 - X-Plane 11.50r1
 - Version 1.6.0-cygnus8

**Comment by magknight1** [comment]
Positive and negative value commands for the following knobs are needed in order to fix the issue, affecting the following datarefs:

- PNL/FLOOD Right: sim/cockpit2/switches/instrument_brightness_ratio[11]
- PNL/FLOOD Left: sim/cockpit2/switches/instrument_brightness_ratio[12]
- MAP light Left: sim/cockpit2/switches/instrument_brightness_ratio[13]
- MAP light Right: sim/cockpit2/switches/instrument_brightness_ratio[10]
- FLT DECK TEMP: aero787/cockpit/overhead/air/fltDeckTemp
- CABIN TEMP: aero787/cockpit/overhead/air/cabinTemp
- AUTOBRAKE: aero787/cockpit/gear/autobrakeKnob

**Comment by aeroniemi** [comment]
just use ATTR_manip_axis_knob rotate_medium 
for flt deck/cabin/brakes/the majority of knobs

**Comment by magknight1** [comment]
Ok. Problem solved.

**Comment by Hinkelstein2** [comment]
Nice, thanks a lot ! I'm not shure, but i think #427 can be closed as well.
